version: '3.8'
services:
  backend:
    image: writenowagency/prompt-generator-backend:${BUILD_NUMBER}
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
      - ./backend/prompts:/app/prompts

  frontend:
    image: writenowagency/prompt-generator-frontend:${BUILD_NUMBER}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_logs:
  backend_uploads:
  backend_prompts:
